README.md
Fixes links to fetch spec and a typo.
=> Fix links to fetch spec

index.js
=> Removing unused requires

assets/module-template.js.t, tests/acceptance/root-test.js
FormData, Blob, and FileReader need to be on the self object, otherwise thinks they aren't supported
=> fix form data and blob compat

.bowerrc, .eslintrc.js, .travis.yml, appveyor.yml, bower.json, package.json, tests/dummy/config/targets.js, tests/test-helper.js, yarn.lock
Upgrading dependencies and ember-cli
=> [DEPENDENCY]: upgraded to ember-cli v2.13.0-beta.4

assets/browser-fetch.js.t, tests/acceptance/root-test.js, tests/dummy/app/controllers/index.js, tests/dummy/app/templates/index.hbs
@stefanpenner This branch includes the changes made by @rwjblue but I added some tests that asserts ember automatically awaits for fetch requests to finish.
=> Wait in tests

index.d.ts, package.json
A simple type def file I'm using to build apps with ember -thought to see if @stefanpenner and @krisselden agree on what I've got here
=> [TYPESCRIPT]: added early index.d.ts for type defs

addon/mixins/adapter-fetch.js, tests/unit/mixins/adapter-fetch-test.js
=> Add hook into fetch behavior

assets/browser-fetch.js.t, tests/acceptance/root-test.js, tests/dummy/app/controllers/index.js, tests/dummy/app/templates/index.hbs
@stefanpenner This contains your in #37 (plus a fixed typo) and a failing test that was failing before your change and it is working after.
=> Rejection must be forwarded

CHANGELOG.md
=> Add CHANGELOG through 3.0.1

README.md
Copy/paste revealed this minor typo 😛
=> fix minor typo around DS

addon/mixins/adapter-fetch.js, tests/unit/mixins/adapter-fetch-test.js
=> fix 'serializeQueryParams' typo

testem.js
=> fix tests on appveyor and in dev

appveyor.yml
I don't really know what I am doing here :) I just realised that bunch of tests used to pass with 0.12...
=> update node in appveyor (remove node 0.12)

.travis.yml, appveyor.yml, testem.js
I *think* I got all the requisite changes. I'm not sure either AppVeyor or Travis normally *change* the configs from what's on `master` when building and testing PRs like this, though?
=> Remove PhantomJS for CI.

README.md
=> Update README.md to reflect yetch usage instead of whatwg-fetch

README.md, addon/mixins/adapter-fetch.js
=> consolidate polyfill imports

package.json, yarn.lock
As mentioned in https://github.com/ember-cli/ember-fetch/pull/143#discussion_r234526068, this was included by mistake.
=> Revert ember-cli-eslint

.travis.yml, appveyor.yml, config/ember-try.js, package.json
Copy pasting travis config from ember-addon-output, and add node versions
=> sync CI scripts with ember-cli output

package.json
We shall later major bump to drop node 6
https://github.com/emberjs/data/pull/6048
=> Fix dep, pin ember-data for node 6

package.json, yarn.lock
=> Upgrade ember-source to pickup transpilation fix

package.json, yarn.lock
=> Bump broccoli-concat to pick up transitive dependency fix

.travis.yml, assets/browser-fetch.js.t, ember-cli-build.js, package.json, yarn.lock
Fix https://github.com/ember-cli/ember-fetch/issues/547
=> Fix whatwg-fetch 3.4 global object name change compatibility

index.d.ts
fixes #716 
`yarn test` passes
=> fix typedef for fetch to match spec
