ember-cli/ember-fetch

- package.json
For some reason, npm installed 0.7.0 (I assume "^0.7.0" should install 0.9.0 too?), which failed my code because i used `response.ok`... It works now with 0.9.0, I bump here so I don't have to update all my package.json files in the future :)
> Bump fetch to 0.9.0

- README.md
Renamed deprecated `ember install:addon` to `ember install`. This feature has been deprecated since Ember CLI v0.2.3, for more information see the [release notes](https://github.com/ember-cli/ember-cli/blob/master/CHANGELOG.md#023).
> Renamed deprecated `ember install:addon`

- index.js
This fixes #26. ember-network provides a file named vendor/fetch.js, which can overwrite the one that comes from this addon.
Why would you have both ember-network and ember-fetch? In my case it was because ember-simple-auth was pulling in ember-network without my realizing.
In general I think addons should try to use their own name when placing things in vendor, so they don't compete over common names.
> Avoid hidden filename collision with ember-network

- assets/browser-fetch.js.t
This has been fundamentally supported when using $.ajax based requests for quite some time (since at least Ember 1.8ish).
This change brings testing parity to ember-fetch...
> Allow automatic "waiting" in tests.

- README.md
- addon/mixins/adapter-fetch.js
- app/mixins/adapter-fetch.js
- package.json
- tests/unit/mixins/adapter-fetch-test.js
- yarn.lock
I would have liked to do some more testing of the adapter methods, let's discuss how best to do that.
> Ember Data Adapter Mixin to use fetch

- addon/mixins/adapter-fetch.js
- tests/unit/mixins/adapter-fetch-test.js
Without this change, the code in `ajaxSuccess` will fail:
```
ajaxSuccess(response, bodyPromise, requestData) {
const headersObject = headersToObject(response.headers);
return bodyPromise.then((body) => {   // {} has no `then`
```
@stefanpenner @cibernox
> Empty response should yield Promise not empty object

- addon/mixins/adapter-fetch.js
- tests/unit/mixins/adapter-fetch-test.js
Instead of relying on the `Content-Length` header, we should assume that response's with status code of 204, 205, or `HEAD` requests won't have bodies and all other responses will.
@stefanpenner
> Better handle empty body responses

- addon/mixins/adapter-fetch.js
- tests/unit/mixins/adapter-fetch-test.js
Originally this logic just checked if the `Content-Type` header already existed, but it needs to check whether the request is a GET request and whether the request has a body.
Original logic from RestAdapter#ajaxOptions:
```
if (hash.data && type !== 'GET') {
hash.contentType = 'application/json; charset=utf-8';
hash.data = JSON.stringify(hash.data);
}
```
Removed default content-type header from test adapter to make tests easier to understand.
> Fix logic for automatically adding a Content-Type header

- addon/mixins/adapter-fetch.js
- tests/unit/mixins/adapter-fetch-test.js
jQuery.ajax behaviors to mimic:
* Default to method `GET` if one is not provided.
* If the `url` in options already has query params, handle this when we process `options.data` to add additional query params.
Increase robustness:
* `headersToObject` should not error if no headers come back from the server.
* `ajaxError` should have a default  empty object for its `response` arg in the case where the fetch request throws an error and there is no response.
> Mimic $.ajax behavior, improve robustness

- addon/mixins/adapter-fetch.js
- tests/unit/mixins/adapter-fetch-test.js
jQuery.ajax filters out undefined/null query params, but not during serialization (hence why I missed this).
> Filter out query params with undefined values, as $.ajax does

- addon/mixins/adapter-fetch.js
- tests/unit/mixins/adapter-fetch-test.js
Fetch expects the body of a POST request to be one of several special objects
```
Note: The body type can only be a Blob, BufferSource, FormData, URLSearchParams, USVString
or ReadableStream type, so for adding a JSON object to the payload you need to stringify
that object.
```
Have `mungOptionsForFetch` take care of this for us.
> Stringify data for a POST request

- addon/mixins/adapter-fetch.js
- tests/unit/mixins/adapter-fetch-test.js
In ember data, both the ajaxError and ajaxSuccess methods receive the payload that was returned from the server. Bringing this adapter more inline with how those function.
Would be nice to be able to, in the future, rework these so that we can just call the super method and return those instead of rewriting all the logic ourselves in these methods.
Going to close #59 in favor of this solution.
> Brought the ajaxError and ajaxSuccess methods more inline with standard ember data methods

- .gitignore
- .travis.yml
- config/ember-try.js
- ember-cli-build.js
- package.json
- testem.js
- tests/dummy/app/app.js
- tests/dummy/config/environment.js
- tests/dummy/config/targets.js
- tests/helpers/module-for-acceptance.js
- yarn.lock
In order to run apps without a dependency on ember-cli-shims, addons that reference the "ember" module must be running ember-cli-babel 6.8.0+. Bump that dependency and generally update Ember-CLI. Expand ember-try to the 2.12 LTS.
> Bump Ember-CLI, ember-cli-babel

- addon/mixins/adapter-fetch.js
- tests/unit/mixins/adapter-fetch-test.js
Previously ([eabb092](https://github.com/ember-cli/ember-fetch/commit/eabb092cdc038a408f7733bc6d02b7bd08d0f4ea)), empty `options.data` objects weren't processed. This commit restores that logic.
Additionally, we were incorrectly removing queryParams with `null` values, when it should have only been params with a value of `undefined`. This has been corrected.
> Don't process empty options.data, don't filter out 'null' query param values

- addon/mixins/adapter-fetch.js
- tests/unit/mixins/adapter-fetch-test.js
There is no reason to call DS.RESTAdapter's `ajaxOptions` as most of the work is jQuery specific and not needed. Additionally, moving `mungOptionsForFetch` to `ajaxOptions` instead of `_ajaxRequest` better mimics ED's patterns.
This PR:
* Overrides `DS.RESTAdapter#ajaxOptions`
* Adds test for this mixin's `ajaxOptions`
> Override Ember Data's ajaxOptions

- addon/mixins/adapter-fetch.js
- tests/unit/mixins/adapter-fetch-test.js
Made a mistake with my last commit (691d1ba98099332813a354ff148082462b0bd84c), which removed the functionality provided by this [line](https://github.com/emberjs/data/blob/v2.14.10/addon/adapters/rest.js#L1120).
That's now been corrected and tests have been added.
@rwjblue @cibernox
> Restore POST body being stringified

- app/mixins/adapter-fetch.js
I think this was added by mistake, and since the readme doesn't make use of it, I don't think it is a breaking change to remove it.
> remove app re-export of mixin

- assets/browser-fetch.js.t
To permit this library to be used when there is no ember-cli-shims addon in the host app, drop the modules usage in `browser-fetch.js`. Instead, reach for the global `Ember` object directly.
> Drop runtime Ember module usage

- addon/mixins/adapter-fetch.js
- tests/unit/mixins/adapter-fetch-test.js
Fixes a bug in the last commit that excluded non-POST requests from getting their request body set (fixes #86).
* Fixes issue
* add tests to catch in the future
@rwjblue @jcao219
> Fix non GET/HEAD requests having no body set

- index.d.ts
In ember-fetch, we're never using the old/Node-style imports that `export =` is meant to support. We just need to declare the module name, and this works as expected. (I've tested locally in my own app.)
> Switch typings to ES-style module

- README.md
Users are having issues using this addon in a Fastboot app (#97), so adding instructions on how to circumvent the issue until it can be solved in ember-cli-fastboot
> Add steps to make ember-fetch work with Fastboot to README

- testem.js
Travis tests are failing with an error about sandbox permissions.
[Failing job](https://travis-ci.org/ember-cli/ember-fetch/jobs/338158266)
```
not ok 1 Chrome - error
---
message: >
Error: Browser exited unexpectedly
Non-zero exit code: null
Stderr: 
[0206/191937.229848:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/google/chrome/chrome-sandbox is owned by root and has mode 4755.
```
According to [this Travis CI doc](https://github.com/travis-ci/docs-travis-ci-com/blob/c1da4af0b7ee5de35fa4490fa8e0fc4b44881089/user/chrome.md#sandboxing), we should be running `--no-sandbox`
> Try to fix Travis tests

- README.md
should be `fastboot/initializers/ajax.js`, not `app/...`
> fix fastboot section of readme

- addon/mixins/adapter-fetch.js
- tests/unit/mixins/adapter-fetch-test.js
A correction to PR #50 and #66 (cc: @nlfurniss).
```js
// jQuery.ajax (tested on 1.11.3, and 3.0)
let body = {
a: undefined,
b: null,
c: 'test'
};
// pretty much what $.ajax does with params
let r = $.ajaxSetup({}, { data: body });
r = $.param(r.data);
console.log(r); // "b=&c=test"
```
> Change serializeQueryParams behavior to match jQuery.

- assets/browser-fetch.js.t
- index.js
- package.json
- public/fastboot-fetch.js
- tests/unit/abortcontroller-test.js
- yarn.lock
> Use yetch and support AbortController

- package.json
Fixes an error (introduced in #112) that occurs whenever a fastboot-enabled app that uses ember-fetch tries to handle a request:
```
There was an error running your app in fastboot. More info about the error:
Error: Unable to require module 'abortcontroller-polyfill/dist/cjs-ponyfill' because it was not in the whitelist.
at Object.require (/app/node_modules/fastboot/src/ember-app.js:133:15)
at Module.callback (/app/tmp/broccoli_merge_trees-output_path-76mgNO0Y.tmp/ember-fetch/fastboot-fetch.js:4:44)
```
> Add a missing fastboot dependencies whitelist entry.

- index.js
Fixes #119.
When the ember-fetch.js file is eventully pulled into vendor.js and minifcation with source map generation is enabled, a rogue sourceMappingURL comment sneaks in and breaks everything. This PR removes that rogue comment.
> fix(build): disable source map generation for concatenation

- README.md
For https://github.com/ember-cli/ember-fetch/issues/55 https://github.com/ember-cli/ember-fetch/issues/98.
To encourage host app to install `ember-fetch` seems to be a right thing to do rather than a "workaround".
Any thoughts on this or alternatives? @kratiahuja @stefanpenner
> Add doc for Fastboot nested addon

- index.js
- package.json
- test/prefer-native-test.js
- yarn.lock
rollup dependencies being wrapped for iife format
Previous way of including the built umd from deps directly gives us the unnecessary wrapper which triggers https://github.com/ember-cli/loader.js/issues/60 in some situations
Needs discussion: 
- should we rollup the [babel-plugin-external-helpers](https://github.com/mo/abortcontroller-polyfill/blob/master/rollup.config.js#L32)?
- pre-rollup deps and ship them?
> Rollup dependencies

- CHANGELOG.md
- package.json
- yarn.lock
babel 5 doesn't support `preset`, explicitly put babel 6 as dep to avoid issues like https://github.com/ember-cli/ember-fetch/issues/127
> Add babel-core@6 to dep since rollup-plugin-babel has it as peer-dep

- addon/mixins/adapter-fetch.js
- addon/utils/serialize-query-params.js
- tests/unit/mixins/adapter-fetch-test.js
- tests/unit/utils/serialize-query-params-test.js
This extracts serializeQueryParams from adapter-fetch such that consuming addons and apps can use query param serialization without the need for the adapter. This was extracted so that ember-data can better migrate away from jquery's ajax :)
> Move serializeQueryParams out of the provided adapter

- .eslintrc.js
- .travis.yml
- addon/mixins/adapter-fetch.js
- config/ember-try.js
- index.js
- package.json
- yarn.lock
Deprecations
- Ember.Logger(RFC297)
- Ember.merge(RFC340)
ember-try version compatibility now covers back to ember2.3
@rwjblue The [deprecation guide](https://emberjs.com/deprecations/v3.x#toc_ember-polyfills-deprecate-merge) says `Ember.assign` is not available in Ember <= 2.4, but I found it in [old release branches](https://github.com/emberjs/ember.js/blob/lts-2-4/packages/ember-metal/lib/assign.js). Am I missing anything here?
Also use whatwg-fetch instead of forked version. Breaking changes include:
- [unsupported body type](https://github.com/github/fetch/commit/08bc7423c9d26dd9f21905fee3b83660723e2d37)
- [Change `credentials` default value to `same-origin`](https://github.com/github/fetch/commit/048626722124b45ed7bc58ec841822610f08798b)
Related PR …
> Deprecate Logger and merge

- addon/mixins/adapter-fetch.js
- tests/unit/mixins/adapter-fetch-test.js
This brings the mixin inline with jQuery.ajax, which correctly returns `undefined` for the body of a 204/205/HEAD response/request since those are not allowed to contain a body.
> Set body to undefined for 204/205/HEAD responses

- addon/mixins/adapter-fetch.js
- tests/unit/mixins/adapter-fetch-test.js
If the user passes a string for `options.data`, we should assume it's already been stringified, and not stringify it again
> If POST body is a string, don't stringify it

- .travis.yml
- package.json
- test/prefer-native-test.js
Make Node tests runnable on Node 6.
~~Note: does not yet actually run these tests in CI.~~
> refactor(test/prefer-native): use co instead of async fn & run in CI

- .eslintignore
- .eslintrc.js
- .gitignore
- package.json
- yarn.lock
> Improve ESLint setup

- index.js
- package.json
- test/prefer-native-test.js
- yarn.lock
This should fix #156 and now also skips some transpilation steps if `config/targets.js` is configured to e.g. support native ES6 classes.
Closes #163 (no longer necessary)
@dbouwman @buschtoens can you test this in your app please? 🙏 
/cc @xg-wang @rwjblue
>  Use `ember-cli-babel` to transpile vendor tree 

- README.md
- addon/mixins/adapter-fetch.js
- fastboot/instance-initializers/setup-fetch.js
- index.js
- package.json
- public/fastboot-fetch.js
- tests/dummy/config/environment.js
- yarn.lock
This PR overrides https://github.com/ember-cli/ember-fetch/pull/128, fixes https://github.com/ember-cli/ember-fetch/issues/138 https://github.com/ember-cli/ember-fetch/issues/110
Implementation stolen from https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/fastboot/initializers/ajax.js
Also upgrade node-fetch to 2.3, which has the abort support
TODO:
- automatic test (or just manual test?)
> Enable Fastboot relative URL

- package.json
This ensures that polyfill will be listed in `dist/package.json`'s `dependencies`
at build, and then properly installed in FastBoot application server.
closes #115, and also closes https://github.com/simplabs/ember-simple-auth/issues/1690, ~~but requires https://github.com/ember-fastboot/fastboot/pull/200~~, using both whitelisted package and module path, which allows to do not wait on the PR, `abortcontroller-polyfill/dist/cjs-ponyfill` can be removed later.
> Use package name of AbortController polyfill in whitelisted dependencies

- index.js
- test/prefer-native-test.js
This makes sure that all nested dependencies use the correct application configuration, and that the import/configuration works in nested addons, especially in engines.
This fixes #133.
I tried it in an app of ours with engines & nested dependencies to ember-fetch, and this ensures that it always got the correct options passed.
Note: While investigating this, I also found out that it wasn't even taking the correct options for building. E.g. If, in my engines dummy app, I had `preferNative: true` specified in the `ember-cli-build.js`, it never actually got to this value, instead reading the config from ember-fetch's config (somehow? not entirely sure).
> Make configuration work in engines

- package.json
- yarn.lock
closes https://github.com/ember-cli/ember-fetch/pull/179
> Upgrade abortcontroller-polyfill for webkit-based browsers fix

- addon/utils/mung-options-for-fetch.js
- tests/unit/utils/mung-options-for-fetch-test.js
Currently `mungOptionsforFetch` only supports String and POJO. This fixes that.
Also add a change that forces `method/type` to uppercase since every time we use it in a conditional we assert against GET/POST/etc.
Please pay special attention to [this line](https://github.com/ember-cli/ember-fetch/compare/master...nlfurniss:support-form-data?expand=1#diff-eb175c7d911802afe9d9b29676a4ce85R31). I'm trying to not build a big switch statement to accomplish this
> Support POST body of all valid types

- addon/mixins/adapter-fetch.js
- addon/utils/mung-options-for-fetch.js
- tests/unit/mixins/adapter-fetch-test.js
- tests/unit/utils/mung-options-for-fetch-test.js
Came across some code I should have moved in 9917ba094ed94cb419144c690d5f4c1ea7216c59. 
Currently, every request that doesn't have a content-type header set is being set to `application/json` (to mimic logic in ED's adapter). This breaks the incoming logic from #174 where the browser needs to set the content-type header correctly for FormData.
> Only set default Content-Type header in adapter mixin

- addon/utils/mung-options-for-fetch.js
- tests/unit/utils/mung-options-for-fetch-test.js
The new Object detection in 6.3.0 for checking when to stringify data does not work for objects that don't have a prototype. I didn't think this would be a common case, but it turns out we ran into it when using Ember's `hash` helper - I reconstructed the issue in this twiddle:
https://ember-twiddle.com/865249c0847b7465f53f0d025bab95aa?openFiles=templates.application.hbs%2C
> handle stringifying data that was created with Object.create(null)

- README.md
- assets/browser-fetch.js.t
- index.js
- package.json
- test/browsers-target-test.js
- yarn.lock
This is my stab at fixing #45.
If the target browsers all support native fetch, this will avoid importing the polyfill(s) and just setup the exports, so that you can continue using `import fetch from 'fetch';` with no code changes.
By default, it will use your specified target browsers, but you can also override this in the options, e.g.:
```js
'ember-fetch': {
preferNative: true,
browers: ['ie 11']
}
```
If no browsers are found at all, it will always include the polyfill.
This PR is on top of #172 , as I could not get to the configuration via `this.buildConfig` in the `treeForBrowserFetch` method.
If you have any suggestions for improvements, I'd be happy to try to implement them - To be honest, it was a bit tricky to implement this, so there might be better ways to do some things.
As a …
> Do not include polyfill if browser targets don't need it

- package.json
ember-cli-addon-tests link the addon it self into node_modules so we need to compile ts to js for tests.
Fix #259
> Wrap mocha tests with ts compile

- index.js
If an ember addon has a modified/overrided treeFor* method, the result of this treeFor method won't get cached, according to https://github.com/ember-cli/ember-cli/blob/master/lib/models/addon.js#L728. The `cacheKeyForTree('vendor')` will always return `null`, so if "ember-fetch" was depended by the app and other addons(e.g ember-data), it will recalculate the "treeForVendor" every time.
This PR make sure that the result of "treeForVendor" will be cached.
> Update cacheKeyForTree to cache the treeForVendor

- .eslintrc.js
- README.md
- addon/errors.ts
- tests/acceptance/error-test.js
- tests/unit/error-test.js
- tests/unit/utils/determine-body-promise-test.js
Transitioning from `ember-ajax` to `ember-fetch` and noticed there weren't any [error detection helpers](https://github.com/ember-cli/ember-ajax#error-detection-helpers)
This PR adds similar helpers, mostly a copy/paste. Main motivation is to aid in transitioning between the two.
```js
import {
isNotFoundResponse,
isForbiddenResponse
} from 'ember-fetch/errors';
```
I looked through npm briefly to see if something similar already existed, but couldn't find anything. If we want to move forward with this, I can add some documentation to the readme.
> Add fetch response and error utils

- public/fetch-fastboot.js
- test/fastboot-test.js
- test/fixtures/dummy/app/routes/index.js
- test/fixtures/dummy/app/templates/index.hbs
Overrides https://github.com/ember-cli/ember-fetch/pull/356, fixes https://github.com/ember-cli/ember-fetch/issues/355.
> The problem is that node-fetch parses input argument in Request's constructor, so any changes made after that are not taken into account, and the request fails with Only absolute URLs are supported error.
> Also, the url property is marked as read-only https://developer.mozilla.org/en-US/docs/Web/API/Request/url, so no changes should be made on that property.
> Enable absolute url transform for Request in FastBoot

- fastboot/instance-initializers/setup-fetch.js
- public/fetch-fastboot.js
- test/fastboot-fetch-test.js
ember-cli-fastboot requires configuring host whitelist before accessing
host from request. In ember-fetch, the error should be lazily thrown.
fix: #371 cc @rwjblue @pzuraq
> fix: throwing w/ fresh ember-cli-fastboot serve

- README.md
I put it in the README to make it the easiest to find and because I wanted to get the suggestion down before I forgot, but I am completely open to alternative suggestions :)
I had to do some spelunking because the deprecation mentions `FetchAdapter` but the documentation names the default export as `AdapterFetch` to match the module name.
> Add section to the README for deprecations

- index.js
This PR adds a check to enforce top-level dependency requirement for ember-fetch addon.
> Added a check to enforce top-level dependency #290.

- .release-it.json
- CHANGELOG.md
- RELEASE.md
- package.json
- yarn.lock
Similar setup as https://github.com/ember-fastboot/ember-cli-fastboot/pull/694/commits/7b045a5aa18863744ad3a6ba5449a71bc9de377d
Also picks v6.7.2 changelog, it somehow got created outside master branch (exactly the reason we need this \_(:з」∠)\_
> Add release-it

- index.js
- test/without-fastboot-build-test.js
hi @xg-wang :
i am doing work on reducing assets files size for deploy.
there is no ember-cli-fastboot in my project , so can we remove fetch-fastboot file in outputTree ? .
> Ignore fastboot build output file if app unused/disable fastboot

- tests/acceptance/error-test.js
The tests for `ember-fetch/errors` were erroneously removed in #447 because `ember-fetch/errors` was originally slated to be removed in that PR, that change was reverted, but then the change to remove the tests was not. I've restored the tests accordingly and ensured that they still pass.
> Restore erroneously removed test for ember-fetch/errors

- yarn.lock
This removes + rebuilds the `yarn.lock` file in an attempt to reproduce the issue that is causing the following error for folks:
> fetch is not defined - maybe your browser targets are not covering everything you need
As reported in #547
> Re-roll yarn.lock file.

- addon/types.ts
Removes the restriction of the data property having to be type of PlainObject where only the properties are strings, objects with strings or an array of objects containing strings. Allow objects will null or undefined properties
> Updates the type for data property to be less restrictive.

- .travis.yml
- assets/browser-fetch.js.t
- config/ember-try.js
- index.js
- package.json
A minimal fix for #600. We should probably follow through with the refactor suggested by @rwjblue in #600 but that can be done later.
This is probably not very embroider friendly, but neither is the current code. It's probably easier to just rewrite the shims in terms of ES modules and embroider macros, i.e. what was suggested in #337.
> Fix ember global

- .travis.yml
- README.md
- assets/browser-fetch.js.t
- ember-cli-build.js
- index.js
I initially tried to get it to work with using `require('rsvp')` when building with Embroider.
However, I couldn't get it to run. I tried adding `rsvp` as a dedicated dependency, as well as `ember-auto-import`, and importing RSVP in an initializer, but nothing made it available under `require('rsvp')` in my embroider app.
I ended up adding an option that allows to opt out of using the RSVP wrapper at all. I think this is an acceptable and backwards compatible opt-out option that should be OK for apps that target only browsers that do not target IE11 anymore.
Let me know if you think this works, or if a different approach would work better.
Closes https://github.com/ember-cli/ember-fetch/issues/622
> Allow to use native promises instead of RSVP

- package.json
- tests/index.html
- yarn.lock
Need to upgrade in order for ember-canary tests to not fail right out of the gate
> Upgrade ember-qunit

- .eslintignore
How was this not there before? 🤔
> add node_modules to eslintignore

- addon/utils/determine-body-promise.ts
Per #430, we shouldn’t console log this in production
> Replace console.warn with Ember.debug
